config/routes.rb
Rails.application.routes.draw do

  post 'checkout', to: 'stripe#checkout'
  get  'checkout/success', to: 'stripe#success', as: 'successful_checkout'

  resources :sessions, only: [:new, :create, :destroy]
  get 'logout', to: 'sessions#destroy'

  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'cookies', to: 'cookies#index'
  resources :authors, only: [ :index, :show, :new, :create ]
  # resources :recipes, only: [ :index, :show, :new, :create, :edit, :update ]
  resources :recipes
  root to: 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :recipes
    has_many :mentees, class_name: 'Author', foreign_key: 'mentor_id'
    belongs_to :mentor, class_name: 'Author', optional: true
    has_many :comments, as: :commentable

    def display_name
        [ first_name, last_name ].join(' ')
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :commentable, polymorphic: true
end

app/models/cookbook.rb
class Cookbook < ApplicationRecord
    has_many :pages
    has_many :recipes, through: :pages
    has_many :comments, as: :commentable
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_and_belongs_to_many :recipes
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :recipe
  belongs_to :cookbook
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :author
    has_and_belongs_to_many :ingredients
    has_many :pages
    has_many :cookbooks, through: :pages
    has_many :comments, as: :commentable

    accepts_nested_attributes_for :comments

    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def authenticate_user
      user_id = session[:user_id].to_i
      return true if current_user

      redirect_to new_session_path
    end

    def current_user
      user_id = session[:user_id].to_i
      User.find_by(id: user_id)
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    skip_before_action :verify_authenticity_token 
    def index
        @authors = Author.all
    end

    def show
        @author = Author.find params['id']
    end

    def new
        @author = Author.new
    end

    def create
        @author = Author.new permitted_params
        respond_to do |format|
            if @author.save
                format.html { redirect_to author_path(@author) }
            else
                format.html { render :new }
            end
        end
    end

    def permitted_params
        params.require(:author).permit(:first_name, :last_name)
    end
end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController
    def index
        cookies[:count] ||= 0
        # cookies[:count] = cookies[:count] || 0

        cookies[:count] = cookies[:count].to_i + 1
        # cookies[:count] += 1
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    # before_action :authenticate_user, only: %i[new create edit update destroy]
    before_action :authenticate_user, except: :index
    before_action :set_recipe, only: [:show, :edit, :update, :destroy]

    def index
      @recipes = Recipe.all
    end

    def show
    end

    def new
      @recipe = Recipe.new
    end

    def edit
    end

    def create
      @recipe = Recipe.new(recipe_params)

      respond_to do |format|
        if @recipe.save
          upload_file
          format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @recipe.update(recipe_params)
          upload_file
          format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def upload_file
      if uploaded_file = params[:recipe][:local_image]
        pathname = Rails.root.join 'public', 'images', uploaded_file.original_filename
        File.open(pathname, 'wb') do |file|
          file.write uploaded_file.read
        end
        @recipe.update_attribute :image_filename, uploaded_file.original_filename
      end
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(
          :name, :description, :difficulty, :author_id, :image, ingredient_ids: [], comments_attributes: [ :body ]
      )
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to recipes_path if session[:user_id]
  end

  def create
    user = User.find_by email: params['email']
    if user && user.authenticate(params['password'])
      session[:user_id] = user.id
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path
  end
end

app/controllers/stripe_controller.rb
class StripeController < ApplicationController
    skip_before_action :verify_authenticity_token

    def checkout
        session = Stripe::Checkout::Session.create({
            payment_method_types: ['card'],
            line_items: [{
            price_data: {
                currency: 'usd',
                product_data: {
                name: 'T-shirt',
                },
                unit_amount: 2000,
            },
            quantity: 1,
            }],
            mode: 'payment',
            # For now leave these URLs as placeholder values.
            #
            # Later on in the guide, you'll create a real success page, but no need to
            # do it yet.
            success_url: successful_checkout_url,
            cancel_url: 'https://example.com/cancel',
        })

        render json: { id: session.id }
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stripe_helper.rb
module StripeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/index.html.erb
<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.first_name %></td>
        <td><%= author.last_name %></td>
        <td><%= link_to 'Show', author_path(author) %></td>
        <td><%#= link_to 'Edit', edit_author_path(author) %></td>
        <td>&nbsp;<%#= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%# <form action='/authors' method='post'>
    <label>First Name</label>
    <input type='text' name='author[first_name]'/>
 
    <label>Last Name</label>
    <input type='text' name='author[last_name]'/>

    <input type='submit' name='commit'>
</form> %>

<%= form_with model: @author do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <%= f.submit 'Submit' %>
<% end %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @author.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @author.last_name %>
</p>

<%= link_to 'Back', authors_path %>

app/views/cookies/index.html.erb
<h1>Cookies</h1>
<p>You have come to this site <%= cookies[:count] %> times</p>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :local_image %>
    <%= form.file_field :local_image %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :difficulty %>
    <%= form.range_field :difficulty, in: 1..5 %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.collection_select :author_id, Author.all, :id, :display_name %>
  </div>

  <div class="field">
    <%= form.label :ingredients %>
    <%= form.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |b| %>
      <%= b.label do %>
        <%= b.check_box + b.text %>
      <% end %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.fields_for :comments, recipe.comments.build do |comment_form| %>
      <%= comment_form.text_area :body %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render 'form', recipe: @recipe %>
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Difficulty</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.description %></td>
        <td><%= recipe.difficulty %></td>
        <td><%= recipe.author_id %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%#= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Recipe', new_recipe_path, class: "newRecipeButton" %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<h2>hey bby <h2>
<%= render 'form', recipe: @recipe %>
<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <strong>Difficulty:</strong>
  <%= @recipe.difficulty %>
</p>

<p>
  <strong>Author:</strong>
  <%= @recipe.author_id %>
  <%= @recipe.author.display_name %>
</p>

<button id="checkout-button">Purchase</button>

<% if @recipe.image_filename %>
  <hr/>
  <h6>Local Image</h6>
  <%= image_tag "/images/#{@recipe.image_filename}", width: '250px' %>
<% end %>

<% if @recipe.image %>
  <hr/>
  <h6>S3 Image</h6>
  <%= image_tag @recipe.image, width: '250px'  %>
<% end %>

  <script type="text/javascript">
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe('<%= Rails.application.credentials.dig(:stripe, :public_key) %>');
    var checkoutButton = document.getElementById('checkout-button');

    checkoutButton.addEventListener('click', function() {
      // Create a new Checkout Session using the server-side endpoint you
      // created in step 3.
      fetch('/checkout', {
        method: 'POST',
      })
      .then(function(response) {
        return response.json();
      })
      .then(function(session) {
        return stripe.redirectToCheckout({ sessionId: session.id });
      })
      .then(function(result) {
        // If `redirectToCheckout` fails due to a browser or network
        // error, you should display the localized error message to your
        // customer using `error.message`.
        if (result.error) {
          alert(result.error.message);
        }
      })
      .catch(function(error) {
        console.error('Error:', error);
      });
    });
  </script>

app/views/stripe/success.html.erb
    <h1>Thanks for your order!</h1>
    <p>
      Recipes-r-us appreciates your business!
      If you have any questions, please email
      <a href="mailto:orders@example.com">orders@example.com</a>.
    </p>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>